export const colleges = [
  {
    name: 'Abendkolleg E-Technologies',
    topic: 'Technik',
    school: 'HTL Bulme Graz',
    link: 'https://www.bulme.at/e-technologies-17-plus/e-technologies-abendkolleg/',
    color: 'bg-bulme_e_technologie',
    image: 'https://picsum.photos/seed/etech/800/600',
    mode: 'Abendkolleg',
  },
  {
    name: 'Abendkolleg Elektronik & Technische Informatik',
    topic: 'Technik',
    school: 'HTL Bulme Graz',
    link: 'https://www.bulme.at/elektronik-technische-informatik-17-plus/elektronik-und-technische-informatik-abend-htl-2/',
    color: 'bg-bulme_elektrotechnik',
    image: 'https://picsum.photos/seed/eti/800/600',
    mode: 'Abendkolleg',
  },
  {
    name: 'Abendkolleg Maschinenbau',
    topic: 'Technik',
    school: 'HTL Bulme Graz',
    link: 'https://www.bulme.at/e-technologies-17/maschinenbau-abendkolleg/',
    color: 'bg-bulme_maschinenbau',
    image: 'https://picsum.photos/seed/maschinenbau1/800/600',
    mode: 'Abendkolleg',
  },
  {
    name: 'Kolleg für Informatik für Berufstätige',
    topic: 'Informatik',
    school: 'Ingenium Education',
    link: 'https://www.ingenium.co.at/studium/informatik/it-kolleg',
    color: 'bg-ingenium',
    image: 'https://picsum.photos/seed/it-kolleg/800/600',
    mode: 'Abendkolleg',
  },
  {
    name: 'Abendkolleg Kolleg für Bautechnik',
    topic: 'Bautechnik',
    school: 'HTL Ortweinschule',
    link: 'https://www.ortweinschule.at/kolleg-und-aufbaulehrgang/',
    color: 'bg-ortwein',
    image: 'https://picsum.photos/seed/bautechnik/800/600',
    mode: 'Abendkolleg',
  },
  {
    name: 'Tageskolleg Kolleg für Bautechnik',
    topic: 'Bautechnik',
    school: 'HTL Ortweinschule',
    link: 'https://www.ortweinschule.at/kolleg-und-aufbaulehrgang/',
    color: 'bg-ortwein',
    image: 'https://picsum.photos/seed/bautechnik/800/600',
    mode: 'Tageskolleg',
  },
  {
    name: 'Kolleg für Chemie',
    topic: 'Naturwissenschaft',
    school: 'Chemie Akademie',
    link: 'https://chemie-akademie.at/chemie-kolleg-home-page/',
    color: 'bg-chemie_kolleg',
    image: 'https://picsum.photos/seed/chemie/800/600',
  },
  {
    name: 'Kolleg für Fine Art Photography & MultimediaArt',
    topic: 'Kunst und Design',
    school: 'HTL Ortweinschule',
    link: 'https://www.ortweinschule.at/portfolio/fine-art-photography-und-multimediaart-18/',
    color: 'bg-ortwein',
    image: 'https://picsum.photos/seed/photography/800/600',
  },
  {
    name: 'Kolleg für Grafik- und Kommunikationsdesign',
    topic: 'Kunst und Design',
    school: 'HTL Ortweinschule',
    link: 'https://www.ortweinschule.at/portfolio/abendkolleg-grafik-und-kommunikationsdesign/',
    color: 'bg-ortwein',
    image: 'https://picsum.photos/seed/design1/800/600',
  },
  {
    name: 'Tageskolleg Informatik',
    topic: 'Informatik',
    school: 'HTL Bulme Graz',
    link: 'https://www.bulme.at/elektronik-technische-informatik-17-plus/informatik-tageskolleg/',
    color: 'bg-bulme_informatik',
    image: 'https://picsum.photos/seed/informatik/800/600',
    mode: 'Tageskolleg',
  },
  {
    name: 'Tageskolleg Maschinenbau',
    topic: 'Technik',
    school: 'HTL Bulme Graz',
    link: 'https://www.bulme.at/e-technologies-17/maschinenbau-tageskolleg/',
    color: 'bg-bulme_maschinenbau',
    image: 'https://picsum.photos/seed/maschinenbau2/800/600',
    mode: 'Tageskolleg',
  },
];
