export const colleges = [
    {
        name: "Abendkolleg E-Technologies",
        topic: "Technik",
        school: "HTL Bulme Graz",
        link: "https://www.bulme.at/e-technologies-17-plus/e-technologies-abendkolleg/",
        color: "bg-primary",
        image: "https://picsum.photos/seed/etech/800/600",
    },
    {
        name: "Abendkolleg Elektronik & Technische Informatik",
        topic: "Technik",
        school: "HTL Bulme Graz",
        link: "https://www.bulme.at/elektronik-technische-informatik-17-plus/elektronik-und-technische-informatik-abend-htl-2/",
        color: "bg-primary",
        image: "https://picsum.photos/seed/eti/800/600",
    },
    {
        name: "Abendkolleg Maschinenbau",
        topic: "Technik",
        school: "HTL Bulme Graz",
        link: "https://www.bulme.at/e-technologies-17/maschinenbau-abendkolleg/",
        color: "bg-primary",
        image: "https://picsum.photos/seed/maschinenbau1/800/600",
    },
    {
        name: "IT-Kolleg – Kolleg für Informatik",
        topic: "Informatik",
        school: "Ingenium Education",
        link: "https://www.ingenium.co.at/studium/informatik/it-kolleg",
        color: "bg-primary",
        image: "https://picsum.photos/seed/it-kolleg/800/600",
    },
    {
        name: "Kolleg für Bautechnik (Tag und Abend)",
        topic: "Bau & Architektur",
        school: "HTL Ortweinschule",
        link: "https://www.ortweinschule.at/kolleg-und-aufbaulehrgang/",
        color: "bg-orange",
        image: "https://picsum.photos/seed/bautechnik/800/600",
    },
    {
        name: "Kolleg für Chemie",
        topic: "Naturwissenschaft",
        school: "Chemie Akademie",
        link: "https://chemie-akademie.at/chemie-kolleg-home-page/",
        color: "bg-red",
        image: "https://picsum.photos/seed/chemie/800/600",
    },
    {
        name: "Kolleg für Fine Art Photography & MultimediaArt",
        topic: "Design",
        school: "HTL Ortweinschule",
        link: "https://www.ortweinschule.at/portfolio/fine-art-photography-und-multimediaart-18/",
        color: "bg-pink",
        image: "https://picsum.photos/seed/photography/800/600",
    },
    {
        name: "Kolleg für Grafik- und Kommunikationsdesign",
        topic: "Design",
        school: "HTL Ortweinschule",
        link: "https://www.ortweinschule.at/portfolio/abendkolleg-grafik-und-kommunikationsdesign/",
        color: "bg-pink",
        image: "https://picsum.photos/seed/design1/800/600",
    },
    {
        name: "Tageskolleg Informatik",
        topic: "Informatik",
        school: "HTL Bulme Graz",
        link: "https://www.bulme.at/elektronik-technische-informatik-17-plus/informatik-tageskolleg/",
        color: "bg-primary",
        image: "https://picsum.photos/seed/informatik/800/600",
    },
    {
        name: "Tageskolleg Maschinenbau",
        topic: "Technik",
        school: "HTL Bulme Graz",
        link: "https://www.bulme.at/e-technologies-17/maschinenbau-tageskolleg/",
        color: "bg-primary",
        image: "https://picsum.photos/seed/maschinenbau2/800/600",
    },
];