export const colleges = [
  {
    name: 'E-Technologies (Abendform)',
    topic: 'Technik',
    school: 'HTL Bulme Graz',
    link: 'https://www.bulme.at/e-technologies-17-plus/e-technologies-abendkolleg/',
    color: 'bg-bulme_e_technologie',
    image: '/bulme/e-technologies-card.webp',
    mode: 'Abendkolleg',
  },
  {
    name: 'Elektronik & Technische Informatik (Abendform)',
    topic: 'Technik',
    school: 'HTL Bulme Graz',
    link: 'https://www.bulme.at/elektronik-technische-informatik-17-plus/elektronik-und-technische-informatik-abend-htl-2/',
    color: 'bg-bulme_elektrotechnik',
    image: '/bulme/Kolleg_Elektronik_Abend/elektronik-card.webp',
    mode: 'Abendkolleg',
  },
  {
    name: 'Maschinenbau (Abendform)',
    topic: 'Technik',
    school: 'HTL Bulme Graz',
    link: 'https://www.bulme.at/e-technologies-17/maschinenbau-abendkolleg/',
    color: 'bg-bulme_maschinenbau',
    image: '/bulme/Kolleg_Maschinenbau_Abend/maschinenbau-card.webp',
    mode: 'Abendkolleg',
  },
  {
    name: 'Informatik für Berufstätige',
    topic: 'Informatik',
    school: 'Ingenium Education',
    link: 'https://www.ingenium.co.at/studium/informatik/it-kolleg',
    color: 'bg-ingenium',
    image: '/ingenium/kolleg_informatik_card.webp',
    mode: 'Abendkolleg',
  },
  {
    name: 'Bautechnik (Tages- und Abendform)',
    topic: 'Bautechnik',
    school: 'HTL Ortweinschule',
    link: 'https://www.ortweinschule.at/kolleg-und-aufbaulehrgang/',
    color: 'bg-ortwein',
    image: 'placeholder-image.webp',
  },
  {
    name: 'Chemie',
    topic: 'Chemie',
    school: 'Chemie Akademie',
    link: 'https://chemie-akademie.at/chemie-kolleg-home-page/',
    color: 'bg-chemie_kolleg',
    image: '/chemie/chemie-card.webp',
  },
  {
    name: 'Fine Art Photography & MultimediaArt',
    topic: 'Kunst und Design',
    school: 'HTL Ortweinschule',
    link: 'https://www.ortweinschule.at/portfolio/fine-art-photography-und-multimediaart-18/',
    color: 'bg-ortwein',
    image: 'placeholder-image.webp',
  },
  {
    name: 'Grafik- und Kommunikationsdesign',
    topic: 'Kunst und Design',
    school: 'HTL Ortweinschule',
    link: 'https://www.ortweinschule.at/portfolio/abendkolleg-grafik-und-kommunikationsdesign/',
    color: 'bg-ortwein',
    image: 'placeholder-image.webp',
  },
  {
    name: 'Informatik (Tagesform)',
    topic: 'Informatik',
    school: 'HTL Bulme Graz',
    link: 'https://www.bulme.at/elektronik-technische-informatik-17-plus/informatik-tageskolleg/',
    color: 'bg-bulme_informatik',
    image: '/bulme/informatik-card.webp',
    mode: 'Tageskolleg',
  },
  {
    name: 'Maschinenbau (Tagesform)',
    topic: 'Technik',
    school: 'HTL Bulme Graz',
    link: 'https://www.bulme.at/e-technologies-17/maschinenbau-tageskolleg/',
    color: 'bg-bulme_maschinenbau',
    image: '/bulme/Kolleg_Maschinenbau_Tag/maschinenbau-card.webp',
    mode: 'Tageskolleg',
  },
];
